### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by d3dave** [stephane-martin/deescalate#1]
Hi, the setup.py script has a bug on line 38. The type returned by get_kernel_version is a list of strings instead of the expected list of ints.

**Comment by stephane-martin** [comment]
Yes that was not so robust. Hopefully platform.uname() will return correct information now.

**Comment by cmcqueen** [comment]
Will you do a new release that is installable with `pip`?

**Comment by sanikolov** [comment]
Stephane, thank you for this python package.
Can you please push the current version to the pypi file server?
On pip installation with python 3.7.x I encountered the issue that @d3dave reported here.
The file that pip is pulling is https://files.pythonhosted.org/packages/e6/7e/25ccc6720f92664ef370c40b1185ac222a23063b115a39a86ae17de60d85/deescalate-0.1.tar.gz .
Hope you can fix that soon.

**Comment by cmcqueen** [comment]
Could you please do a new release that is installable with `pip`.

**Comment by stephane-martin** [comment]
The version 0.1.2 just uploaded on PyPI should be both Python 2 and Python 3 compatible. Please confirm that it works for you.

**Comment by stephane-martin** [comment]
Hi. v0.1.2 has been uploaded to PyPI. On my machine it works with python
3.7 on latest ubuntu.
